spring:
  application:
    name: order-service
server:
  port: 8081

management:
  endpoint:
    health:
      show-details: always

    metrics:
      enabled: true
  endpoints:
    web:
     exposure:
      include: "*"
